image:
  repository: cr.yandex/crpo19gj048i31sr0f6k/leonid.sh
  tag: sha-e533be56b26b8f20e876e30e70bf765f07f3d3ea

gateway:
  enabled: true
  host: leonid.sh
  # Tung Tung Tung Sahur
  # terraform -chdir=cloud_resources/yc output -raw gateway_public_ip
  dnsTarget: "158.160.154.6"
  aliases:
    - host: home.leonid.sh
      dnsTarget: gateway.leonid.sh
    - host: www.leonid.sh
      dnsTarget: gateway.leonid.sh
  clusterIssuer: yc-clusterissuer
