image:
  repository: cr.yandex/crpo19gj048i31sr0f6k/leonid.sh
  tag: sha-1a5597f62d09a153d7adf89f095deeef5dd7577b

gateway:
  enabled: true
  host: leonid.sh
  # Tung Tung Tung Sahur
  # terraform -chdir=cloud_resources/yc output -raw gateway_public_ip
  dnsTarget: "158.160.154.6"
  aliases:
    - host: home.leonid.sh
      dnsTarget: gateway.leonid.sh
    - host: www.leonid.sh
      dnsTarget: gateway.leonid.sh
  clusterIssuer: yc-clusterissuer
