version: "3.9"
services:
  k8s:
    image: k8s.leonid.sh:latest
    container_name: k8s
    network_mode: host
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - TERRAFORM_CLOUD_TOKEN=${TERRAFORM_CLOUD_TOKEN}
      - BASHLY_SOURCE_DIR=/root/k8s.leonid.sh/bashly
      - KUBECONFIG=/root/.kube/hetzner.conf
    volumes:
      - ~/.ssh:/root/.mounted_ssh # I hate Docker on Windows
      - ~/.kube:/root/.kube
      - ./:/root/k8s.leonid.sh
