#!/usr/bin/env bash
# This script was generated by bashly 1.2.10 (https://bashly.dev)
# Modifying it manually is not recommended

# :wrapper.bash3_bouncer
if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
  printf "bash version 4 or higher is required\n" >&2
  exit 1
fi

# :command.master_script

# :command.version_command
version_command() {
  echo "$version"
}

# :command.usage
k8s.leonid.sh_usage() {
  printf "k8s.leonid.sh - k8s.leonid.sh tools\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh COMMAND\n"
  printf "  k8s.leonid.sh [COMMAND] --help | -h\n"
  printf "  k8s.leonid.sh --version | -v\n"
  echo
  # :command.usage_commands
  printf "%s\n" "Commands:"
  printf "  %s   Terraform commands\n" "terraform"
  printf "  %s   Ansible playbooks\n" "ansible  "
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo
    printf "  %s\n" "--version, -v"
    printf "    Show version number\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_terraform_usage() {
  printf "k8s.leonid.sh terraform - Terraform commands\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh terraform COMMAND\n"
  printf "  k8s.leonid.sh terraform [COMMAND] --help | -h\n"
  echo
  # :command.usage_commands
  printf "%s\n" "Commands:"
  printf "  %s   Initialize the Terraform working directory\n" "init   "
  printf "  %s   Generate and show an execution plan\n" "plan   "
  printf "  %s   Build or change infrastructure\n" "apply  "
  printf "  %s   Destroy Terraform-managed infrastructure\n" "destroy"
  printf "  %s   Show output values\n" "output "
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_terraform_init_usage() {
  printf "k8s.leonid.sh terraform init - Initialize the Terraform working directory\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh terraform init\n"
  printf "  k8s.leonid.sh terraform init --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_terraform_plan_usage() {
  printf "k8s.leonid.sh terraform plan - Generate and show an execution plan\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh terraform plan\n"
  printf "  k8s.leonid.sh terraform plan --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_terraform_apply_usage() {
  printf "k8s.leonid.sh terraform apply - Build or change infrastructure\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh terraform apply\n"
  printf "  k8s.leonid.sh terraform apply --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_terraform_destroy_usage() {
  printf "k8s.leonid.sh terraform destroy - Destroy Terraform-managed infrastructure\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh terraform destroy\n"
  printf "  k8s.leonid.sh terraform destroy --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_terraform_output_usage() {
  printf "k8s.leonid.sh terraform output - Show output values\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh terraform output\n"
  printf "  k8s.leonid.sh terraform output --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_ansible_usage() {
  printf "k8s.leonid.sh ansible - Ansible playbooks\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh ansible COMMAND\n"
  printf "  k8s.leonid.sh ansible [COMMAND] --help | -h\n"
  echo
  # :command.usage_commands
  printf "%s\n" "Commands:"
  printf "  %s   Initialize the first Kubernetes control plane node\n" "init_control_plane"
  printf "  %s   Join an additional control plane node\n" "join_ctrl         "
  printf "  %s   Join a worker node\n" "join_worker       "
  printf "  %s   Join a load balancer node (HAProxy only)\n" "join_load_balancer"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_ansible_init_control_plane_usage() {
  printf "k8s.leonid.sh ansible init_control_plane - Initialize the first Kubernetes control plane node\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh ansible init_control_plane [OPTIONS]\n"
  printf "  k8s.leonid.sh ansible init_control_plane --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_flags
    # :flag.usage
    printf "  %s\n" "--public-ipv6 PUBLIC_IPV6 (required)"
    printf "    Public IPv6 address\n"
    echo

    # :flag.usage
    printf "  %s\n" "--internal-ipv4 INTERNAL_IPV4 (required)"
    printf "    Internal IPv4 address\n"
    echo

    # :flag.usage
    printf "  %s\n" "--hostname HOSTNAME"
    printf "    Hostname (default: ctrl-001)\n"
    printf "    %s\n" "Default: ctrl-001"
    echo

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_ansible_join_ctrl_usage() {
  printf "k8s.leonid.sh ansible join_ctrl - Join an additional control plane node\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh ansible join_ctrl [OPTIONS]\n"
  printf "  k8s.leonid.sh ansible join_ctrl --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_flags
    # :flag.usage
    printf "  %s\n" "--public-ipv6 PUBLIC_IPV6 (required)"
    printf "    Public IPv6 address\n"
    echo

    # :flag.usage
    printf "  %s\n" "--internal-ipv4 INTERNAL_IPV4 (required)"
    printf "    Internal IPv4 address\n"
    echo

    # :flag.usage
    printf "  %s\n" "--hostname HOSTNAME (required)"
    printf "    Hostname\n"
    echo

    # :flag.usage
    printf "  %s\n" "--existing-ctrl-public-ipv6 EXISTING_CTRL_PUBLIC_IPV6 (required)"
    printf "    Existing control plane's public IPv6 address\n"
    echo

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_ansible_join_worker_usage() {
  printf "k8s.leonid.sh ansible join_worker - Join a worker node\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh ansible join_worker [OPTIONS]\n"
  printf "  k8s.leonid.sh ansible join_worker --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_flags
    # :flag.usage
    printf "  %s\n" "--public-ipv6 PUBLIC_IPV6 (required)"
    printf "    Public IPv6 address\n"
    echo

    # :flag.usage
    printf "  %s\n" "--internal-ipv4 INTERNAL_IPV4 (required)"
    printf "    Internal IPv4 address\n"
    echo

    # :flag.usage
    printf "  %s\n" "--hostname HOSTNAME (required)"
    printf "    Hostname\n"
    echo

    # :flag.usage
    printf "  %s\n" "--existing-ctrl-public-ipv6 EXISTING_CTRL_PUBLIC_IPV6 (required)"
    printf "    Existing control plane's public IPv6 address\n"
    echo

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_ansible_join_load_balancer_usage() {
  printf "k8s.leonid.sh ansible join_load_balancer - Join a load balancer node (HAProxy only)\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh ansible join_load_balancer [OPTIONS]\n"
  printf "  k8s.leonid.sh ansible join_load_balancer --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_flags
    # :flag.usage
    printf "  %s\n" "--public-ipv6 PUBLIC_IPV6 (required)"
    printf "    Public IPv6 address\n"
    echo

    # :flag.usage
    printf "  %s\n" "--internal-ipv4 INTERNAL_IPV4 (required)"
    printf "    Internal IPv4 address\n"
    echo

    # :flag.usage
    printf "  %s\n" "--worker-internal-ipv4 WORKER_INTERNAL_IPV4 (repeatable)"
    printf "    Additional worker node IP(s) for HAProxy\n"
    echo

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.normalize_input
# :command.normalize_input_function
normalize_input() {
  local arg passthru flags
  passthru=false

  while [[ $# -gt 0 ]]; do
    arg="$1"
    if [[ $passthru == true ]]; then
      input+=("$arg")
    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^-([a-zA-Z0-9][a-zA-Z0-9]+)$ ]]; then
      flags="${BASH_REMATCH[1]}"
      for ((i = 0; i < ${#flags}; i++)); do
        input+=("-${flags:i:1}")
      done
    elif [[ "$arg" == "--" ]]; then
      passthru=true
      input+=("$arg")
    else
      input+=("$arg")
    fi

    shift
  done
}

# :command.inspect_args
inspect_args() {
  if ((${#args[@]})); then
    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
    echo args:
    for k in "${sorted_keys[@]}"; do
      echo "- \${args[$k]} = ${args[$k]}"
    done
  else
    echo args: none
  fi

  if ((${#deps[@]})); then
    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
    echo
    echo deps:
    for k in "${sorted_keys[@]}"; do
      echo "- \${deps[$k]} = ${deps[$k]}"
    done
  fi

  if ((${#env_var_names[@]})); then
    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
    echo
    echo "environment variables:"
    for k in "${sorted_names[@]}"; do
      echo "- \$$k = ${!k:-}"
    done
  fi
}

# :command.command_functions

# :command.function
k8s.leonid.sh_terraform_init_command() {

  # /root/k8s.leonid.sh/bashly/terraform_init_command.sh
  cd cloud_resources
  terraform init
}

# :command.function
k8s.leonid.sh_terraform_plan_command() {

  # /root/k8s.leonid.sh/bashly/terraform_plan_command.sh
  cd cloud_resources
  terraform plan
}

# :command.function
k8s.leonid.sh_terraform_apply_command() {

  # /root/k8s.leonid.sh/bashly/terraform_apply_command.sh
  cd cloud_resources
  terraform apply
}

# :command.function
k8s.leonid.sh_terraform_destroy_command() {

  # /root/k8s.leonid.sh/bashly/terraform_destroy_command.sh
  cd cloud_resources
  terraform destroy
}

# :command.function
k8s.leonid.sh_terraform_output_command() {

  # /root/k8s.leonid.sh/bashly/terraform_output_command.sh
  cd cloud_resources
  terraform output
}

# :command.function
k8s.leonid.sh_ansible_init_control_plane_command() {

  # /root/k8s.leonid.sh/bashly/ansible_init_control_plane_command.sh
  inspect_args

  public_ipv6="${args['--public-ipv6']}"
  internal_ipv4="${args['--internal-ipv4']}"
  hostname="${args['--hostname']}"

  echo "Debugging Arguments:"
  echo "Public IPv6: $public_ipv6"
  echo "Internal IPv4: $internal_ipv4"
  echo "Hostname: $hostname"

  ansible-playbook playbooks/init_control_plane.yaml \
    --private-key "~/.ssh/k8s.leonid.sh" \
    -e "public_ipv6=$public_ipv6 \
        internal_ipv4=$internal_ipv4 \
        hostname=$hostname \
        ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"

}

# :command.function
k8s.leonid.sh_ansible_join_ctrl_command() {

  # /root/k8s.leonid.sh/bashly/ansible_join_ctrl_command.sh
  inspect_args

  public_ipv6="${args['--public-ipv6']}"
  internal_ipv4="${args['--internal-ipv4']}"
  hostname="${args['--hostname']}"
  existing_ctrl_public_ipv6="${args['--existing-ctrl-public-ipv6']}"

  echo "Debugging Arguments:"
  echo "Public IPv6: $public_ipv6"
  echo "Internal IPv4: $internal_ipv4"
  echo "Hostname: $hostname"
  echo "Existing Control Plane IPv6: $existing_ctrl_public_ipv6"

  ansible-playbook playbooks/join_ctrl.yaml \
    --private-key "~/.ssh/k8s.leonid.sh" \
    -e "public_ipv6=$public_ipv6 \
        internal_ipv4=$internal_ipv4 \
        hostname=$hostname \
        existing_ctrl_public_ipv6=$existing_ctrl_public_ipv6 \
        ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"

}

# :command.function
k8s.leonid.sh_ansible_join_worker_command() {

  # /root/k8s.leonid.sh/bashly/ansible_join_worker_command.sh
  inspect_args

  public_ipv6="${args['--public-ipv6']}"
  internal_ipv4="${args['--internal-ipv4']}"
  hostname="${args['--hostname']}"
  existing_ctrl_public_ipv6="${args['--existing-ctrl-public-ipv6']}"

  echo "Debugging Arguments:"
  echo "Public IPv6: $public_ipv6"
  echo "Internal IPv4: $internal_ipv4"
  echo "Hostname: $hostname"
  echo "Existing Control Plane IPv6: $existing_ctrl_public_ipv6"

  ansible-playbook playbooks/join_worker.yaml \
    --private-key "~/.ssh/k8s.leonid.sh" \
    -e "public_ipv6=$public_ipv6 \
        internal_ipv4=$internal_ipv4 \
        hostname=$hostname \
        existing_ctrl_public_ipv6=$existing_ctrl_public_ipv6 \
        ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"

}

# :command.function
k8s.leonid.sh_ansible_join_load_balancer_command() {

  # /root/k8s.leonid.sh/bashly/ansible_join_load_balancer_command.sh
  inspect_args

  public_ipv6="${args['--public-ipv6']}"
  internal_ipv4="${args['--internal-ipv4']}"
  worker_internal_ipv4="${args['--worker-internal-ipv4']}"

  echo "Debugging Arguments:"
  echo "Public IPv6: $public_ipv6"
  echo "Internal IPv4: $internal_ipv4"
  echo "Worker IP(s) for HAProxy: $worker_internal_ipv4"

  ansible-playbook playbooks/join_load_balancer.yaml \
    --private-key "~/.ssh/k8s.leonid.sh" \
    -e "public_ipv6=$public_ipv6 \
        internal_ipv4=$internal_ipv4 \
        worker_internal_ipv4='$worker_internal_ipv4' \
        ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"

}

# :command.parse_requirements
parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --version | -v)
        version_command
        exit
        ;;

      --help | -h)
        long_usage=yes
        k8s.leonid.sh_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action=${1:-}

  case $action in
    -*) ;;

    terraform)
      action="terraform"
      shift
      k8s.leonid.sh_terraform_parse_requirements "$@"
      shift $#
      ;;

    ansible)
      action="ansible"
      shift
      k8s.leonid.sh_ansible_parse_requirements "$@"
      shift $#
      ;;

    # :command.command_fallback
    "")
      k8s.leonid.sh_usage >&2
      exit 1
      ;;

    *)
      printf "invalid command: %s\n" "$action" >&2
      exit 1
      ;;

  esac

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.parse_requirements
k8s.leonid.sh_terraform_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_terraform_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action=${1:-}

  case $action in
    -*) ;;

    init)
      action="init"
      shift
      k8s.leonid.sh_terraform_init_parse_requirements "$@"
      shift $#
      ;;

    plan)
      action="plan"
      shift
      k8s.leonid.sh_terraform_plan_parse_requirements "$@"
      shift $#
      ;;

    apply)
      action="apply"
      shift
      k8s.leonid.sh_terraform_apply_parse_requirements "$@"
      shift $#
      ;;

    destroy)
      action="destroy"
      shift
      k8s.leonid.sh_terraform_destroy_parse_requirements "$@"
      shift $#
      ;;

    output)
      action="output"
      shift
      k8s.leonid.sh_terraform_output_parse_requirements "$@"
      shift $#
      ;;

    # :command.command_fallback
    "")
      k8s.leonid.sh_terraform_usage >&2
      exit 1
      ;;

    *)
      printf "invalid command: %s\n" "$action" >&2
      exit 1
      ;;

  esac

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.parse_requirements
k8s.leonid.sh_terraform_init_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_terraform_init_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="terraform init"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.parse_requirements
k8s.leonid.sh_terraform_plan_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_terraform_plan_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="terraform plan"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.parse_requirements
k8s.leonid.sh_terraform_apply_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_terraform_apply_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="terraform apply"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.parse_requirements
k8s.leonid.sh_terraform_destroy_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_terraform_destroy_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="terraform destroy"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.parse_requirements
k8s.leonid.sh_terraform_output_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_terraform_output_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="terraform output"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.parse_requirements
k8s.leonid.sh_ansible_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_ansible_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action=${1:-}

  case $action in
    -*) ;;

    init_control_plane)
      action="init_control_plane"
      shift
      k8s.leonid.sh_ansible_init_control_plane_parse_requirements "$@"
      shift $#
      ;;

    join_ctrl)
      action="join_ctrl"
      shift
      k8s.leonid.sh_ansible_join_ctrl_parse_requirements "$@"
      shift $#
      ;;

    join_worker)
      action="join_worker"
      shift
      k8s.leonid.sh_ansible_join_worker_parse_requirements "$@"
      shift $#
      ;;

    join_load_balancer)
      action="join_load_balancer"
      shift
      k8s.leonid.sh_ansible_join_load_balancer_parse_requirements "$@"
      shift $#
      ;;

    # :command.command_fallback
    "")
      k8s.leonid.sh_ansible_usage >&2
      exit 1
      ;;

    *)
      printf "invalid command: %s\n" "$action" >&2
      exit 1
      ;;

  esac

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.parse_requirements
k8s.leonid.sh_ansible_init_control_plane_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_ansible_init_control_plane_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="ansible init_control_plane"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      # :flag.case
      --public-ipv6)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--public-ipv6']="$2"
          shift
          shift
        else
          printf "%s\n" "--public-ipv6 requires an argument: --public-ipv6 PUBLIC_IPV6" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --internal-ipv4)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--internal-ipv4']="$2"
          shift
          shift
        else
          printf "%s\n" "--internal-ipv4 requires an argument: --internal-ipv4 INTERNAL_IPV4" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --hostname)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--hostname']="$2"
          shift
          shift
        else
          printf "%s\n" "--hostname requires an argument: --hostname HOSTNAME" >&2
          exit 1
        fi
        ;;

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

  # :command.required_flags_filter
  if [[ -z ${args['--public-ipv6']+x} ]]; then
    printf "missing required flag: --public-ipv6 PUBLIC_IPV6\n" >&2
    exit 1
  fi
  if [[ -z ${args['--internal-ipv4']+x} ]]; then
    printf "missing required flag: --internal-ipv4 INTERNAL_IPV4\n" >&2
    exit 1
  fi

  # :command.default_assignments
  [[ -n ${args['--hostname']:-} ]] || args['--hostname']="ctrl-001"

}

# :command.parse_requirements
k8s.leonid.sh_ansible_join_ctrl_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_ansible_join_ctrl_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="ansible join_ctrl"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      # :flag.case
      --public-ipv6)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--public-ipv6']="$2"
          shift
          shift
        else
          printf "%s\n" "--public-ipv6 requires an argument: --public-ipv6 PUBLIC_IPV6" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --internal-ipv4)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--internal-ipv4']="$2"
          shift
          shift
        else
          printf "%s\n" "--internal-ipv4 requires an argument: --internal-ipv4 INTERNAL_IPV4" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --hostname)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--hostname']="$2"
          shift
          shift
        else
          printf "%s\n" "--hostname requires an argument: --hostname HOSTNAME" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --existing-ctrl-public-ipv6)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--existing-ctrl-public-ipv6']="$2"
          shift
          shift
        else
          printf "%s\n" "--existing-ctrl-public-ipv6 requires an argument: --existing-ctrl-public-ipv6 EXISTING_CTRL_PUBLIC_IPV6" >&2
          exit 1
        fi
        ;;

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

  # :command.required_flags_filter
  if [[ -z ${args['--public-ipv6']+x} ]]; then
    printf "missing required flag: --public-ipv6 PUBLIC_IPV6\n" >&2
    exit 1
  fi
  if [[ -z ${args['--internal-ipv4']+x} ]]; then
    printf "missing required flag: --internal-ipv4 INTERNAL_IPV4\n" >&2
    exit 1
  fi
  if [[ -z ${args['--hostname']+x} ]]; then
    printf "missing required flag: --hostname HOSTNAME\n" >&2
    exit 1
  fi
  if [[ -z ${args['--existing-ctrl-public-ipv6']+x} ]]; then
    printf "missing required flag: --existing-ctrl-public-ipv6 EXISTING_CTRL_PUBLIC_IPV6\n" >&2
    exit 1
  fi

}

# :command.parse_requirements
k8s.leonid.sh_ansible_join_worker_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_ansible_join_worker_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="ansible join_worker"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      # :flag.case
      --public-ipv6)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--public-ipv6']="$2"
          shift
          shift
        else
          printf "%s\n" "--public-ipv6 requires an argument: --public-ipv6 PUBLIC_IPV6" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --internal-ipv4)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--internal-ipv4']="$2"
          shift
          shift
        else
          printf "%s\n" "--internal-ipv4 requires an argument: --internal-ipv4 INTERNAL_IPV4" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --hostname)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--hostname']="$2"
          shift
          shift
        else
          printf "%s\n" "--hostname requires an argument: --hostname HOSTNAME" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --existing-ctrl-public-ipv6)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--existing-ctrl-public-ipv6']="$2"
          shift
          shift
        else
          printf "%s\n" "--existing-ctrl-public-ipv6 requires an argument: --existing-ctrl-public-ipv6 EXISTING_CTRL_PUBLIC_IPV6" >&2
          exit 1
        fi
        ;;

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

  # :command.required_flags_filter
  if [[ -z ${args['--public-ipv6']+x} ]]; then
    printf "missing required flag: --public-ipv6 PUBLIC_IPV6\n" >&2
    exit 1
  fi
  if [[ -z ${args['--internal-ipv4']+x} ]]; then
    printf "missing required flag: --internal-ipv4 INTERNAL_IPV4\n" >&2
    exit 1
  fi
  if [[ -z ${args['--hostname']+x} ]]; then
    printf "missing required flag: --hostname HOSTNAME\n" >&2
    exit 1
  fi
  if [[ -z ${args['--existing-ctrl-public-ipv6']+x} ]]; then
    printf "missing required flag: --existing-ctrl-public-ipv6 EXISTING_CTRL_PUBLIC_IPV6\n" >&2
    exit 1
  fi

}

# :command.parse_requirements
k8s.leonid.sh_ansible_join_load_balancer_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_ansible_join_load_balancer_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="ansible join_load_balancer"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      # :flag.case
      --public-ipv6)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--public-ipv6']="$2"
          shift
          shift
        else
          printf "%s\n" "--public-ipv6 requires an argument: --public-ipv6 PUBLIC_IPV6" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --internal-ipv4)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--internal-ipv4']="$2"
          shift
          shift
        else
          printf "%s\n" "--internal-ipv4 requires an argument: --internal-ipv4 INTERNAL_IPV4" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --worker-internal-ipv4)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          escaped="$(printf '%q' "$2")"
          if [[ -z ${args['--worker-internal-ipv4']+x} ]]; then
            args['--worker-internal-ipv4']="$escaped"
          else
            args['--worker-internal-ipv4']="${args['--worker-internal-ipv4']} $escaped"
          fi
          shift
          shift
        else
          printf "%s\n" "--worker-internal-ipv4 requires an argument: --worker-internal-ipv4 WORKER_INTERNAL_IPV4" >&2
          exit 1
        fi
        ;;

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

  # :command.required_flags_filter
  if [[ -z ${args['--public-ipv6']+x} ]]; then
    printf "missing required flag: --public-ipv6 PUBLIC_IPV6\n" >&2
    exit 1
  fi
  if [[ -z ${args['--internal-ipv4']+x} ]]; then
    printf "missing required flag: --internal-ipv4 INTERNAL_IPV4\n" >&2
    exit 1
  fi

}

# :command.initialize
initialize() {
  declare -g version="0.1.0"
  set -e

}

# :command.run
run() {
  # :command.globals
  declare -g long_usage=''
  declare -g -A args=()
  declare -g -A deps=()
  declare -g -a env_var_names=()
  declare -g -a input=()

  normalize_input "$@"
  parse_requirements "${input[@]}"

  case "$action" in
    "terraform") k8s.leonid.sh_terraform_command ;;
    "terraform init") k8s.leonid.sh_terraform_init_command ;;
    "terraform plan") k8s.leonid.sh_terraform_plan_command ;;
    "terraform apply") k8s.leonid.sh_terraform_apply_command ;;
    "terraform destroy") k8s.leonid.sh_terraform_destroy_command ;;
    "terraform output") k8s.leonid.sh_terraform_output_command ;;
    "ansible") k8s.leonid.sh_ansible_command ;;
    "ansible init_control_plane") k8s.leonid.sh_ansible_init_control_plane_command ;;
    "ansible join_ctrl") k8s.leonid.sh_ansible_join_ctrl_command ;;
    "ansible join_worker") k8s.leonid.sh_ansible_join_worker_command ;;
    "ansible join_load_balancer") k8s.leonid.sh_ansible_join_load_balancer_command ;;
  esac
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  initialize
  run "$@"
fi
