#!/usr/bin/env bash
# This script was generated by bashly 1.2.7 (https://bashly.dannyb.co)
# Modifying it manually is not recommended

# :wrapper.bash3_bouncer
if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
  printf "bash version 4 or higher is required\n" >&2
  exit 1
fi

# :command.master_script

# :command.version_command
version_command() {
  echo "$version"
}

# :command.usage
k8s.leonid.sh_usage() {
  printf "k8s.leonid.sh - k8s.leonid.sh tools\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh COMMAND\n"
  printf "  k8s.leonid.sh [COMMAND] --help | -h\n"
  printf "  k8s.leonid.sh --version | -v\n"
  echo
  # :command.usage_commands
  printf "%s\n" "Commands:"
  printf "  %s   Terraform commands\n" "terraform"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo
    printf "  %s\n" "--version, -v"
    printf "    Show version number\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_terraform_usage() {
  printf "k8s.leonid.sh terraform - Terraform commands\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh terraform COMMAND\n"
  printf "  k8s.leonid.sh terraform [COMMAND] --help | -h\n"
  echo
  # :command.usage_commands
  printf "%s\n" "Commands:"
  printf "  %s   Initialize the Terraform working directory\n" "init   "
  printf "  %s   Generate and show an execution plan\n" "plan   "
  printf "  %s   Build or change infrastructure\n" "apply  "
  printf "  %s   Destroy Terraform-managed infrastructure\n" "destroy"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_terraform_init_usage() {
  printf "k8s.leonid.sh terraform init - Initialize the Terraform working directory\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh terraform init\n"
  printf "  k8s.leonid.sh terraform init --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_terraform_plan_usage() {
  printf "k8s.leonid.sh terraform plan - Generate and show an execution plan\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh terraform plan\n"
  printf "  k8s.leonid.sh terraform plan --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_terraform_apply_usage() {
  printf "k8s.leonid.sh terraform apply - Build or change infrastructure\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh terraform apply\n"
  printf "  k8s.leonid.sh terraform apply --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.usage
k8s.leonid.sh_terraform_destroy_usage() {
  printf "k8s.leonid.sh terraform destroy - Destroy Terraform-managed infrastructure\n\n"

  printf "%s\n" "Usage:"
  printf "  k8s.leonid.sh terraform destroy\n"
  printf "  k8s.leonid.sh terraform destroy --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.normalize_input
# :command.normalize_input_function
normalize_input() {
  local arg passthru flags
  passthru=false

  while [[ $# -gt 0 ]]; do
    arg="$1"
    if [[ $passthru == true ]]; then
      input+=("$arg")
    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^-([a-zA-Z0-9][a-zA-Z0-9]+)$ ]]; then
      flags="${BASH_REMATCH[1]}"
      for ((i = 0; i < ${#flags}; i++)); do
        input+=("-${flags:i:1}")
      done
    elif [[ "$arg" == "--" ]]; then
      passthru=true
      input+=("$arg")
    else
      input+=("$arg")
    fi

    shift
  done
}

# :command.inspect_args
inspect_args() {
  if ((${#args[@]})); then
    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
    echo args:
    for k in "${sorted_keys[@]}"; do
      echo "- \${args[$k]} = ${args[$k]}"
    done
  else
    echo args: none
  fi

  if ((${#deps[@]})); then
    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
    echo
    echo deps:
    for k in "${sorted_keys[@]}"; do
      echo "- \${deps[$k]} = ${deps[$k]}"
    done
  fi

  if ((${#env_var_names[@]})); then
    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
    echo
    echo "environment variables:"
    for k in "${sorted_names[@]}"; do
      echo "- \$$k = ${!k:-}"
    done
  fi
}

# :command.command_functions

# :command.function
k8s.leonid.sh_terraform_init_command() {

  # /root/k8s.leonid.sh/bashly/terraform_init_command.sh
  cd cloud_resources
  terraform init
}

# :command.function
k8s.leonid.sh_terraform_plan_command() {

  # /root/k8s.leonid.sh/bashly/terraform_plan_command.sh
  cd cloud_resources
  terraform plan
}

# :command.function
k8s.leonid.sh_terraform_apply_command() {

  # /root/k8s.leonid.sh/bashly/terraform_apply_command.sh
  cd cloud_resources
  terraform apply
}

# :command.function
k8s.leonid.sh_terraform_destroy_command() {

  # /root/k8s.leonid.sh/bashly/terraform_destroy_command.sh
  cd cloud_resources
  terraform destroy
}

# :command.parse_requirements
parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --version | -v)
        version_command
        exit
        ;;

      --help | -h)
        long_usage=yes
        k8s.leonid.sh_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action=${1:-}

  case $action in
    -*) ;;

    terraform)
      action="terraform"
      shift
      k8s.leonid.sh_terraform_parse_requirements "$@"
      shift $#
      ;;

    # :command.command_fallback
    "")
      k8s.leonid.sh_usage >&2
      exit 1
      ;;

    *)
      printf "invalid command: %s\n" "$action" >&2
      exit 1
      ;;

  esac

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.parse_requirements
k8s.leonid.sh_terraform_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_terraform_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action=${1:-}

  case $action in
    -*) ;;

    init)
      action="init"
      shift
      k8s.leonid.sh_terraform_init_parse_requirements "$@"
      shift $#
      ;;

    plan)
      action="plan"
      shift
      k8s.leonid.sh_terraform_plan_parse_requirements "$@"
      shift $#
      ;;

    apply)
      action="apply"
      shift
      k8s.leonid.sh_terraform_apply_parse_requirements "$@"
      shift $#
      ;;

    destroy)
      action="destroy"
      shift
      k8s.leonid.sh_terraform_destroy_parse_requirements "$@"
      shift $#
      ;;

    # :command.command_fallback
    "")
      k8s.leonid.sh_terraform_usage >&2
      exit 1
      ;;

    *)
      printf "invalid command: %s\n" "$action" >&2
      exit 1
      ;;

  esac

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.parse_requirements
k8s.leonid.sh_terraform_init_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_terraform_init_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="terraform init"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.parse_requirements
k8s.leonid.sh_terraform_plan_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_terraform_plan_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="terraform plan"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.parse_requirements
k8s.leonid.sh_terraform_apply_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_terraform_apply_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="terraform apply"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.parse_requirements
k8s.leonid.sh_terraform_destroy_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        k8s.leonid.sh_terraform_destroy_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="terraform destroy"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.initialize
initialize() {
  version="0.1.0"
  long_usage=''
  set -e

  # :command.globals
  declare -g -A args=()
  declare -g -A deps=()
  declare -g -a env_var_names=()
  declare -g -a input=()

}

# :command.run
run() {
  normalize_input "$@"
  parse_requirements "${input[@]}"

  case "$action" in
    "terraform") k8s.leonid.sh_terraform_command ;;
    "terraform init") k8s.leonid.sh_terraform_init_command ;;
    "terraform plan") k8s.leonid.sh_terraform_plan_command ;;
    "terraform apply") k8s.leonid.sh_terraform_apply_command ;;
    "terraform destroy") k8s.leonid.sh_terraform_destroy_command ;;
  esac
}

initialize
run "$@"
