apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-tenant
  sources:
    - repoURL: "https://operator.min.io"
      chart: tenant
      targetRevision: "7.0.1"
      helm:
        valueFiles:
          - "$values/argocd/minio-tenant/values.yaml"
    - repoURL: "git@github.com:matyushinleonid/k8s.leonid.sh.git"
      targetRevision: HEAD
      ref: values
      path: argocd/minio-tenant # Has to be specified so the raw manifests can be discovered
      directory:
        exclude: 'argoapp.yaml'