tenant:
  name: minio-tenant
  namespace: minio-tenant
  credsSecret:
    name: minio-tenant-creds
  pools:
    - name: pool-0
      servers: 3
      volumesPerServer: 2
      size: 3Gi
      storageClassName: local-path
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: minio
            topologyKey: "kubernetes.io/hostname"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
  mountPath: /export
  certificate:
    requestAutoCert: true
ingress:
  api:
    enabled: true
    ingressClassName: kong
    host: "minio.leonid.sh"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
    path: /
    pathType: Prefix
    tls:
      - hosts:
          - minio.leonid.sh
        secretName: minio-tenant-tls