apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  sources:
    - repoURL: "https://charts.konghq.com"
      chart: kong
      targetRevision: "2.48.0"
      helm:
        valueFiles:
          - "$values/argocd/kong/values.yaml"
    - repoURL: "git@github.com:matyushinleonid/k8s.leonid.sh.git"
      targetRevision: HEAD
      ref: values