terraform_project_dir: "{{ playbook_dir }}/../../cloud_resources/yc"
tf_outputs_file: "{{ lookup('env', 'TF_OUTPUTS_FILE') | default('', true) }}"

kubeconfig_path: "{{ lookup('env', 'KUBECONFIG') | default(playbook_dir + '/../.kube/k8s-leonid-sh.yaml', true) }}"
yc_command: yc
yc_profile: "{{ lookup('env', 'YC_PROFILE') | default('', true) }}"
yc_get_credentials_external: true
kubectl_command: kubectl

argocd_namespace: argocd
argocd_chart_repo_name: argo
argocd_chart_repository: https://argoproj.github.io/argo-helm
argocd_chart_ref: argo/argo-cd
argocd_chart_version: 9.7.1
argocd_values_file: "{{ playbook_dir }}/../../argocd/platform/argocd/values.yaml"

argocd_repo_url: git@github.com:matyushinleonid/k8s.leonid.sh.git
argocd_repo_creds_url: git@github.com:matyushinleonid
argocd_target_revision: HEAD
argocd_root_path: argocd
argocd_command: argocd
argocd_sync_timeout: 600
argocd_sync_retry_limit: 5
argocd_sync_retry_backoff_duration: 5s
argocd_sync_retry_backoff_factor: 2
argocd_sync_retry_backoff_max_duration: 1m
argocd_platform_applications:
  - external-secrets
  - node-local-dns
  - node-sitter
  - ingress-nginx
  - cert-manager
  - external-dns
  - argocd
  - loki-stack
  - kube-prometheus-stack
