global:
  domain: argocd.leonid.sh

configs:
  params:
    server.insecure: true
  cm:
    resource.customizations: |
      networking.k8s.io/Ingress:
        health.lua: |
          hs = {}
          hs.status = "Healthy"
          hs.message = "Probably just fine"
          return hs
      admissionregistration.k8s.io/ValidatingWebhookConfiguration:
        ignoreDifferences: |
          jqPathExpressions:
          - '.webhooks[].clientConfig.caBundle'
      v1/Secret:
        ignoreDifferences: |
          jqPathExpressions:
          - '.data.tls.crt'
          - '.data.tls.key'

server:
  ingress:
    enabled: true
    ingressClassName: "kong"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      konghq.com/protocols: "https"
      konghq.com/https-redirect-status-code: "301"
    extraTls:
      - hosts:
          - argocd.leonid.sh
        secretName: argocd-tls