apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: yc-lockbox
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    yandexlockbox:
      fetching:
        byID: {}
      auth:
        authorizedKeySecretRef:
          name: yc-lockbox-auth
          namespace: external-secrets
          key: authorized-key
