apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-operator
  sources:
    - repoURL: "https://operator.min.io"
      chart: operator
      targetRevision: "7.0.1"
      helm:
        valueFiles:
          - "$values/argocd/minio-operator/values.yaml"
    - repoURL: "git@github.com:matyushinleonid/k8s.leonid.sh.git"
      targetRevision: HEAD
      ref: values