apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mothership
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/matyushinleonid/k8s.leonid.sh.git
    targetRevision: HEAD
    path: argocd/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy: {}