apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: docker.io/envoyproxy
      chart: gateway-helm
      targetRevision: v1.8.2
      helm:
        valueFiles:
          - $values/argocd/platform/envoy-gateway/controller-values.yaml
    - repoURL: git@github.com:matyushinleonid/k8s.leonid.sh.git
      targetRevision: HEAD
      ref: values
    - repoURL: git@github.com:matyushinleonid/k8s.leonid.sh.git
      targetRevision: HEAD
      path: argocd/platform/envoy-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
