apiVersion: batch/v1
kind: CronJob
metadata:
  name: dasein-notifier
  namespace: dasein-ist-endlich-bot
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: dasein-notifier
        spec:
          restartPolicy: OnFailure
          containers:
            - name: notifier
              image: matyushinleonid/dasein-ist-endlich-bot:7a8401ad27bc4545e579ba7fffa4fb835fef4dca
              imagePullPolicy: IfNotPresent
              command: ["/app/dasein-ist-endlich-bot", "notifier", "--config-path", "/configs/local.yaml"]
              envFrom:
                - secretRef:
                    name: dasein-secret
              volumeMounts:
                - name: config-volume
                  mountPath: /configs
                  readOnly: true
          volumes:
            - name: config-volume
              configMap:
                name: dasein-config
                items:
                  - key: local.yaml
                    path: local.yaml