apiVersion: apps/v1
kind: Deployment
metadata:
  name: dasein-deployment
  namespace: dasein-ist-endlich-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dasein
  template:
    metadata:
      labels:
        app: dasein
    spec:
      containers:
        - name: dasein
          image: matyushinleonid/dasein-ist-endlich-bot:638d82fe39abdc1149cfbda629f31e8e62c5ca32
          imagePullPolicy: IfNotPresent
          command: ["/app/dasein-ist-endlich-bot", "listener", "--config-path", "/configs/local.yaml"]
          envFrom:
            - secretRef:
                name: dasein-secret
          volumeMounts:
            - name: config-volume
              mountPath: /configs
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: dasein-config
            items:
              - key: local.yaml
                path: local.yaml