apiVersion: apps/v1
kind: Deployment
metadata:
  name: dasein-deployment
  namespace: dasein-ist-endlich-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dasein
  template:
    metadata:
      labels:
        app: dasein
    spec:
      containers:
        - name: dasein
          image: matyushinleonid/dasein-ist-endlich-bot:cce7621554e89b62b6f2b15d054392e72fc53e26
          imagePullPolicy: IfNotPresent
          command: ["/app/dasein-ist-endlich-bot", "listener", "--config-path", "/configs/local.yaml"]
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          envFrom:
            - secretRef:
                name: dasein-secret
          volumeMounts:
            - name: config-volume
              mountPath: /configs
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: dasein-config
            items:
              - key: local.yaml
                path: local.yaml