{{- if .Values.externalSecret.lockboxSecretId }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-yandex-credentials
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: yc-lockbox
    kind: ClusterSecretStore
  target:
    name: cm-sa-creds
    creationPolicy: Merge
  data:
    - secretKey: key.json
      remoteRef:
        key: {{ .Values.externalSecret.lockboxSecretId | quote }}
        property: authorized-key
{{- end }}
