{{- if .Values.externalSecret.lockboxSecretId }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-yandex-credentials
  namespace: cert-manager
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: yc-lockbox
    kind: ClusterSecretStore
  target:
    name: cm-sa-creds
    creationPolicy: Merge
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        annotations:
          argocd.argoproj.io/tracking-id: cert-manager:/Secret:cert-manager/cm-sa-creds
  data:
    - secretKey: key.json
      remoteRef:
        key: {{ .Values.externalSecret.lockboxSecretId | quote }}
        property: authorized-key
{{- end }}
