apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencanary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:matyushinleonid/k8s.leonid.sh.git
    targetRevision: HEAD
    path: argocd/opencanary
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: opencanary
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
