apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: yc-lockbox
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-user: "{{ .grafana_admin_user }}"
        admin-password: "{{ .grafana_admin_password }}"
  data:
    - secretKey: grafana_admin_user
      remoteRef:
        key: e6qib21hrudo8gun0h48
        property: grafana-admin-user
    - secretKey: grafana_admin_password
      remoteRef:
        key: e6qib21hrudo8gun0h48
        property: grafana-admin-password
