image:
  repository: cr.yandex/crpo19gj048i31sr0f6k/kongzilla
  tag: 0.1.4
  pullPolicy: Always

beacon:
  enabled: true
  replicaCount: 1

gateway:
  enabled: true
  host: kongzilla.leonid.sh
  dnsTarget: gateway.leonid.sh
  clusterIssuer: yc-clusterissuer
