image:
  repository: cr.yandex/crpo19gj048i31sr0f6k/kongzilla
  tag: sha-5eaab7fe55cc12807e388139708a2fc5feb06410
  pullPolicy: Always

beacon:
  enabled: true
  replicaCount: 1

gateway:
  enabled: true
  host: kongzilla.leonid.sh
  dnsTarget: gateway.leonid.sh
  clusterIssuer: yc-clusterissuer
