apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-state-metrics
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-state-metrics
      targetRevision: "5.31.1"
      helm:
        valueFiles:
          - "$values/argocd/kube-state-metrics/values.yaml"
    - repoURL: "git@github.com:matyushinleonid/k8s.leonid.sh.git"
      targetRevision: HEAD
      ref: values