{{- if .Values.externalSecret.lockboxSecretId }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-yandex-credentials
  namespace: external-dns
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: yc-lockbox
    kind: ClusterSecretStore
  target:
    name: external-dns-externaldns
    creationPolicy: Merge
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        annotations:
          argocd.argoproj.io/tracking-id: external-dns:/Secret:external-dns/external-dns-externaldns
  data:
    - secretKey: iamkeyfile.json
      remoteRef:
        key: {{ .Values.externalSecret.lockboxSecretId | quote }}
        property: authorized-key
{{- end }}
