{{- if .Values.externalSecret.lockboxSecretId }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-yandex-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: yc-lockbox
    kind: ClusterSecretStore
  target:
    name: {{ include "externaldns.fullname" . }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: iamkeyfile.json
      remoteRef:
        key: {{ .Values.externalSecret.lockboxSecretId | quote }}
        property: authorized-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
