config:
  folder_id: b1g3o4ahe2b4o5od724t
  auth:
    json: "{}"

externalSecret:
  refreshInterval: 15m
  # Tung Tung Tung Sahur
  # terraform -chdir=cloud_resources/yc output -raw external_dns_lockbox_secret_id
  lockboxSecretId: "e6qjje1p22g2ol13jcjh"
