apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
data:
  gost.yaml: |
    services:
      - name: https-forward-proxy
        addr: ":{{ .Values.proxy.containerPort }}"
        resolver: public-dns
        bypass: denied-destinations
        handler:
          type: http
          auther: lockbox
        listener:
          type: tcp
    authers:
      - name: lockbox
        reload: {{ .Values.proxy.authReloadInterval | quote }}
        file:
          path: /etc/gost/auth/users
    bypasses:
      - name: denied-destinations
        matchers:
          {{- toYaml .Values.proxy.deniedDestinations | nindent 10 }}
    resolvers:
      - name: public-dns
        nameservers:
          {{- range .Values.proxy.dnsServers }}
          - addr: {{ . | quote }}
            prefer: ipv4
          {{- end }}
