apiVersion: v1
kind: Service
metadata:
  name: proxy-public-dns
  namespace: {{ .Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.host | quote }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.gateway.dnsTarget | quote }}
spec:
  type: ExternalName
  externalName: {{ .Values.gateway.dnsTarget | quote }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: proxy
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.gateway.clusterIssuer | quote }}
spec:
  parentRef:
    name: {{ .Values.gateway.name | quote }}
    namespace: {{ .Values.gateway.namespace | quote }}
  listeners:
    - name: https-proxy
      hostname: {{ .Values.host | quote }}
      port: {{ .Values.proxy.publicPort }}
      protocol: TLS
      tls:
        mode: Terminate
        certificateRefs:
          - name: proxy-tls
      allowedRoutes:
        kinds:
          - group: gateway.networking.k8s.io
            kind: TCPRoute
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: proxy
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: proxy
      kind: ListenerSet
      sectionName: https-proxy
  rules:
    - backendRefs:
        - name: proxy
          port: {{ .Values.proxy.containerPort }}
