apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: temporal-postgres
  namespace: temporal
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: yc-lockbox
    kind: ClusterSecretStore
  target:
    name: temporal-postgres
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        password: "{{ .temporal_postgres_password }}"
  data:
    - secretKey: temporal_postgres_password
      remoteRef:
        key: e6qojcm2ke05j3v745t1
        property: temporal_postgres_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: temporal-web-basic-auth
  namespace: temporal
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: yc-lockbox
    kind: ClusterSecretStore
  target:
    name: temporal-web-basic-auth
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        auth: "{{ .htpasswd }}"
  data:
    - secretKey: htpasswd
      remoteRef:
        key: e6qctn3nipag3gtda97u
        property: temporal-web-htpasswd
---
apiVersion: batch/v1
kind: Job
metadata:
  name: temporal-default-namespace
  namespace: temporal
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 20
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app.kubernetes.io/component: namespace-setup
        app.kubernetes.io/instance: temporal
        app.kubernetes.io/name: temporal
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-default-namespace
          image: temporalio/admin-tools:1.31.1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - >-
              temporal operator namespace describe -n default ||
              temporal operator namespace create -n default --retention 3d
          env:
            - name: TEMPORAL_ADDRESS
              value: temporal-frontend.temporal.svc:7233
