server:
  config:
    persistence:
      default:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: "cloudnative-pg-cluster-rw.cloudnative-pg-cluster.svc.cluster.local"
          port: 5432
          database: "temporal"
          user: "postgres"
          existingSecret: temporal-postgres-creds
      visibility:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: "cloudnative-pg-cluster-rw.cloudnative-pg-cluster.svc.cluster.local"
          port: 5432
          database: "temporal_visibility"
          user: "postgres"
          existingSecret: temporal-postgres-creds
      tls:
        frontend:
          server:
            certFile: /etc/temporal/tls/tls.crt
            keyFile: /etc/temporal/tls/tls.key
            requireClientAuth: true
            clientCaFiles:
              - /etc/temporal/tls/tls.crt
          client:
            serverName: temporal.leonid.sh
            rootCaFiles:
              - /etc/temporal/tls/tls.crt
  frontend:
    ingress:
      enabled: true
      className: kong
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - api.temporal.leonid.sh
      tls:
        - secretName: temporal-tls
          hosts:
            - api.temporal.leonid.sh
  additionalVolumes:
    - name: temporal-frontend-tls
      secret:
        secretName: temporal-frontend-tls
  additionalVolumeMounts:
    - name: temporal-frontend-tls
      mountPath: /etc/temporal/tls
      readOnly: true

web:
  ingress:
    enabled: true
    className: kong
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - temporal.leonid.sh
    tls:
      - secretName: temporal-tls
        hosts:
          - temporal.leonid.sh

admintools:
  enabled: false

cassandra:
  enabled: false

mysql:
  enabled: false

grafana:
  enabled: false

elasticsearch:
  enabled: false

prometheus:
  enabled: false