server:
  config:
    persistence:
      default:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: "cloudnative-pg-cluster-rw.cloudnative-pg-cluster.svc.cluster.local"
          port: 5432
          database: "temporal"
          user: "postgres"
          existingSecret: temporal-postgres-creds
      visibility:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: "cloudnative-pg-cluster-rw.cloudnative-pg-cluster.svc.cluster.local"
          port: 5432
          database: "temporal_visibility"
          user: "postgres"
          existingSecret: temporal-postgres-creds

admintools:
  enabled: false

cassandra:
  enabled: false

mysql:
  enabled: false

grafana:
  enabled: false

elasticsearch:
  enabled: false

prometheus:
  enabled: false