host: radio.leonid.sh

defaultStation: govnovoz

stations:
  govnovoz:
    configMapName: radio-liquidsoap
    mount: govnovoz.mp3
    bitrate: 224
    maxListeners: 5
    objectStoragePrefix: radio/govnovoz
  gachi:
    configMapName: radio-gachi
    mount: gachi.mp3
    bitrate: 224
    maxListeners: 5
    objectStoragePrefix: radio/gachi

objectStorage:
  endpoint: storage.yandexcloud.net
  region: ru-central1
  bucket: matyushinleonid
  syncIntervalSeconds: 300
  cacheSizeLimit: 10Gi
  lockboxSecretId: e6q352hr67bnde4kjo5b
  lockboxProperty: s3-yaml

images:
  icecast: libretime/icecast:2.5.0
  liquidsoap: savonet/liquidsoap:v2.4.5
  rclone: rclone/rclone:1.74.2

icecast:
  maxClients: 100
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      memory: 128Mi

liquidsoap:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi

rclone:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
      ephemeral-storage: 512Mi
    limits:
      memory: 128Mi
      ephemeral-storage: 10Gi
