---
- name: Join a load balancer node (no static inventory)
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    public_ipv6: "{{ public_ipv6 }}"
    internal_ipv4: "{{ internal_ipv4 }}"
    worker_ips: >-
      {% if worker_internal_ipv4 is string %}
      ["{{ worker_internal_ipv4 }}"]
      {% elif worker_internal_ipv4 is iterable %}
      {{ worker_internal_ipv4 }}
      {% else %}
      [] 
      {% endif %}

  tasks:
    - name: Add new load balancer node to ephemeral inventory
      add_host:
        name: new_lb
        ansible_host: "{{ public_ipv6 }}"
        ansible_user: root
        ansible_ssh_private_key_file: "~/.ssh/k8s.leonid.sh"

    - name: Parse worker_ips into a list
      set_fact:
        worker_ips_list: "{{ worker_ips | from_json }}"

    - name: Generate HAProxy configuration locally
      shell: ./scripts/prepare_haproxy_config.sh "{{ worker_ips_list | join(' ') }}"
      register: haproxy_config
      failed_when: "'Error:' in haproxy_config.stdout"

- name: Configure the new load balancer node
  hosts: new_lb
  gather_facts: false
  become: true

  vars:
    new_node_ip: "{{ hostvars['localhost'].public_ipv6 }}"

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        force: yes

    - name: Install required packages
      apt:
        name:
          - curl
          - apt-transport-https
          - git
          - wget
          - software-properties-common
          - lsb-release
          - ca-certificates
          - socat
          - haproxy
        state: present
        update_cache: yes

    - name: Overwrite HAProxy configuration
      copy:
        content: "{{ hostvars['localhost'].haproxy_config.stdout + '\n' }}"
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'

    - name: Validate HAProxy configuration
      shell: haproxy -c -f /etc/haproxy/haproxy.cfg
      register: haproxy_validation
      failed_when: haproxy_validation.rc != 0

    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted
