apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.2
    helm:
      values: |
        loki:
          enabled: true
          persistence:
            enabled: true
            storageClassName: yc-network-hdd
            size: 20Gi
          config:
            compactor:
              retention_enabled: true
            limits_config:
              retention_period: 336h
        promtail:
          enabled: true
        grafana:
          enabled: false
          sidecar:
            datasources:
              enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
