controller:
  ingressClassResource:
    name: nginx
  replicaCount: 2
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/instance: ingress-nginx
          app.kubernetes.io/component: controller
  service:
    # Tung Tung Tung Sahur
    # terraform -chdir=cloud_resources/yc output -raw ingress_nginx_public_ip
    loadBalancerIP: "158.160.211.144"
    annotations:
      external-dns.alpha.kubernetes.io/hostname: minecraft.leonid.sh
    externalTrafficPolicy: Cluster
    sessionAffinity: None

tcp:
  "25565": "minecraft/papermc:25565"

portNamePrefix: tcp
