controller:
  ingressClassResource:
    name: nginx
  replicaCount: 2
  service:
    # Tung Tung Tung Sahur
    # terraform -chdir=cloud_resources/yc output -raw ingress_nginx_public_ip
    loadBalancerIP: "158.160.202.21"
    externalTrafficPolicy: Cluster
    sessionAffinity: None
