apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flannel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:matyushinleonid/k8s.leonid.sh.git
    targetRevision: HEAD
    path: argocd/flannel
    directory:
      exclude: 'argoapp.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx