storage:
  # Tung Tung Tung Sahur
  # terraform -chdir=cloud_resources/yc output -raw minecraft_disk_id
  diskId: "fv443sdr4derlf9giaqh"
  capacity: 35Gi
  storageClassName: yc-network-ssd

externalSecret:
  lockboxSecretId: e6q7dr9jusl4saot0mkg

bluemap:
  host: map.minecraft.leonid.sh
  port: 8100
  renderThreadCount: 2
  maps:
    overworld:
      radius: 3000
    nether:
      radius: 1000
    end:
      radius: 1000
  views:
    flat: true
    perspective: false
    freeFlight: false
    hires: false
  web:
    image: nginx:1.30.4-alpine
    resources:
      requests:
        cpu: 5m
        memory: 16Mi
      limits:
        memory: 64Mi
